#!/usr/bin/env python3
"""
Ralph-Loop Agent: Continuous Development Executor

This script implements the AI-powered execution loop that works alongside
ralph-loop.sh to actually implement features.

Usage:
    python3 ralph-loop-agent.py [--once] [--feature ID]
    
Options:
    --once        Run only one iteration
    --feature ID  Work on specific feature ID
"""

import json
import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Tuple


class RalphLoopAgent:
    """Agent that continuously develops features until completion."""
    
    def __init__(self, project_root: str = "."):
        self.project_root = Path(project_root).absolute()
        self.features_file = self.project_root / ".agent" / "features.json"
        self.progress_file = self.project_root / ".agent" / "progress.md"
        self.task_file = self.project_root / ".agent" / "ralph-current-task.md"
        
        self.priority_order = {"critical": 0, "high": 1, "medium": 2, "low": 3}
        self.iteration = 0
        self.completed = 0
        
    def log(self, level: str, message: str):
        """Log message with color coding."""
        colors = {
            "INFO": "\033[0;34m",
            "SUCCESS": "\033[0;32m",
            "WARNING": "\033[1;33m",
            "ERROR": "\033[0;31m",
            "RALPH": "\033[0;35m",
        }
        reset = "\033[0m"
        color = colors.get(level, "")
        print(f"{color}[{level}]{reset} {message}")
    
    def load_features(self) -> Dict:
        """Load features from JSON file."""
        with open(self.features_file, 'r', encoding='utf-8') as f:
            return json.load(f)
    
    def save_features(self, data: Dict):
        """Save features to JSON file."""
        with open(self.features_file, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
    
    def get_pending_features(self, category: str = None, feature_id: str = None) -> List[Dict]:
        """Get list of pending features sorted by priority."""
        data = self.load_features()
        pending = [f for f in data.get('features', []) if not f.get('passes', False)]
        
        # Sort by priority
        pending.sort(key=lambda x: self.priority_order.get(x.get('priority', 'medium'), 2))
        
        # Apply filters
        if feature_id:
            pending = [f for f in pending if f.get('id') == feature_id]
        elif category:
            pending = [f for f in pending if f.get('category', '').lower() == category.lower()]
        
        return pending
    
    def get_next_feature(self, category: str = None, feature_id: str = None) -> Optional[Dict]:
        """Get the next feature to implement."""
        pending = self.get_pending_features(category, feature_id)
        return pending[0] if pending else None
    
    def get_progress_stats(self) -> Tuple[int, int, int, float]:
        """Get progress statistics: (total, completed, pending, percentage)."""
        data = self.load_features()
        features = data.get('features', [])
        total = len(features)
        completed = sum(1 for f in features if f.get('passes', False))
        pending = total - completed
        percentage = round(completed / total * 100, 1) if total > 0 else 0
        return total, completed, pending, percentage
    
    def create_task_file(self, feature: Dict) -> Path:
        """Create a task file for the current feature."""
        feature_id = feature.get('id', 'unknown')
        description = feature.get('description', '')
        priority = feature.get('priority', 'medium')
        category = feature.get('category', '')
        steps = feature.get('steps', [])
        depends_on = feature.get('depends_on')
        
        content = f"""# Ralph-Loop: Current Task

## Feature: {feature_id}

**Priority**: {priority}  
**Category**: {category}  
{f'**Depends on**: {depends_on}' if depends_on else ''}

### Description
{description}

### Verification Steps
{chr(10).join([f'- [ ] {step}' for step in steps])}

### Implementation Instructions

You are in Ralph-Loop continuous development mode. Your task is to:

1. **Implement this feature** following the description above
2. **Follow project conventions** - check existing code patterns
3. **Test thoroughly** - ensure all verification steps pass
4. **Leave clean state** - no half-implemented code

### After Implementation
1. Run tests to verify the feature works
2. Mark feature as complete if all tests pass
3. Commit changes

---
*Generated by Ralph-Loop at {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}*
"""
        
        with open(self.task_file, 'w', encoding='utf-8') as f:
            f.write(content)
        
        return self.task_file
    
    def update_feature_status(self, feature_id: str, passes: bool, notes: str = ""):
        """Update feature status in features.json."""
        data = self.load_features()
        
        for feature in data.get('features', []):
            if feature.get('id') == feature_id:
                feature['passes'] = passes
                if notes:
                    feature['notes'] = notes
        
        # Update metadata
        features = data.get('features', [])
        completed = sum(1 for f in features if f.get('passes', False))
        data['metadata']['completed_features'] = completed
        data['metadata']['completion_percentage'] = round(completed / len(features) * 100, 1) if features else 0
        
        self.save_features(data)
    
    def run_tests(self) -> bool:
        """Run feature tests."""
        test_script = self.project_root / ".agent" / "test-features.sh"
        if test_script.exists():
            result = subprocess.run(
                [str(test_script)],
                cwd=self.project_root,
                capture_output=True,
                text=True
            )
            return result.returncode == 0
        return True
    
    def commit_progress(self, feature_id: str, description: str):
        """Commit current progress."""
        # Check if there are changes
        result = subprocess.run(
            ['git', 'status', '--porcelain'],
            cwd=self.project_root,
            capture_output=True,
            text=True
        )
        
        if not result.stdout.strip():
            return
        
        commit_msg = f"[agent] feat({feature_id}): {description}"
        subprocess.run(['git', 'add', '-A'], cwd=self.project_root)
        subprocess.run(['git', 'commit', '-m', commit_msg], cwd=self.project_root)
    
    def update_progress_file(self, feature_id: str, description: str, status: str):
        """Update progress.md file."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        # Read existing content
        existing = ""
        if self.progress_file.exists():
            with open(self.progress_file, 'r', encoding='utf-8') as f:
                lines = f.readlines()
                # Skip header (first 3 lines)
                existing = ''.join(lines[3:]) if len(lines) > 3 else ''
        
        # Write new content
        content = f"""# iFlow CLI Development Progress

## Current Status
- **Last Updated**: {timestamp}
- **Phase**: Active Development (Ralph-Loop)
- **Active Feature**: {feature_id}

---

## Session History

### Ralph-Loop - {timestamp}
- **Actions**: {status} - {description}
- **Feature**: {feature_id}
- **Status**: {'✅ Completed' if status == 'COMPLETED' else '⚠️ In Progress'}

---

{existing}
"""
        
        with open(self.progress_file, 'w', encoding='utf-8') as f:
            f.write(content)
    
    def show_status(self):
        """Display current progress status."""
        total, completed, pending, percentage = self.get_progress_stats()
        
        print()
        print("╔══════════════════════════════════════════════════════════╗")
        print("║              Ralph-Loop Status Report                    ║")
        print("╚══════════════════════════════════════════════════════════╝")
        print()
        print(f"  📊 Progress: {completed}/{total} ({percentage}%)")
        print(f"  ⏳ Pending: {pending} features")
        print()
        
        if pending > 0:
            print("  📋 Next features:")
            for i, f in enumerate(self.get_pending_features()[:5], 1):
                priority = f.get('priority', 'medium').upper()
                desc = f.get('description', '')[:50]
                print(f"    {i}. [{priority}] {f.get('id')}: {desc}...")
        else:
            print("  🎉 All features complete!")
        print()
    
    def implement_feature(self, feature: Dict) -> bool:
        """
        Implement a single feature.
        
        This method should be called by the AI agent with the actual
        implementation logic. For now, it creates the task file and
        returns True if implementation should proceed.
        """
        feature_id = feature.get('id', 'unknown')
        description = feature.get('description', '')
        
        self.log("RALPH", "═" * 60)
        self.log("RALPH", f"Implementing: {feature_id}")
        self.log("RALPH", "═" * 60)
        print()
        self.log("INFO", f"Description: {description}")
        self.log("INFO", f"Priority: {feature.get('priority', 'medium')} | Category: {feature.get('category', '')}")
        print()
        
        # Create task file
        task_path = self.create_task_file(feature)
        self.log("INFO", f"Task file: {task_path}")
        
        return True
    
    def run_iteration(self, category: str = None, feature_id: str = None) -> bool:
        """
        Run a single iteration of the development loop.
        
        Returns True if there are more features to implement.
        """
        self.iteration += 1
        
        print()
        self.log("RALPH", "─" * 60)
        self.log("RALPH", f"Iteration #{self.iteration}")
        self.log("RALPH", "─" * 60)
        
        # Get next feature
        feature = self.get_next_feature(category, feature_id)
        
        if not feature:
            self.log("SUCCESS", "All features complete! 🎉")
            return False
        
        # Implement feature
        self.implement_feature(feature)
        
        return True
    
    def run_loop(self, max_iterations: int = 100, category: str = None, 
                 feature_id: str = None, once: bool = False):
        """Run the continuous development loop."""
        self.log("RALPH", "Starting Ralph-Loop Continuous Development")
        self.log("RALPH", f"Max iterations: {max_iterations}")
        
        self.show_status()
        
        while self.iteration < max_iterations:
            has_more = self.run_iteration(category, feature_id)
            
            if once or not has_more:
                break
        
        print()
        self.log("RALPH", "═" * 60)
        self.log("RALPH", "Ralph-Loop Completed")
        self.log("RALPH", "═" * 60)
        print()
        self.log("INFO", f"Iterations: {self.iteration}")
        self.log("INFO", f"Features completed this session: {self.completed}")
        self.show_status()


def main():
    import argparse
    
    parser = argparse.ArgumentParser(description="Ralph-Loop Agent")
    parser.add_argument("--once", action="store_true", help="Run only one iteration")
    parser.add_argument("--feature", "-f", help="Work on specific feature ID")
    parser.add_argument("--category", "-c", help="Only work on specific category")
    parser.add_argument("--max-iterations", "-m", type=int, default=100, help="Maximum iterations")
    parser.add_argument("--status", "-s", action="store_true", help="Show status and exit")
    
    args = parser.parse_args()
    
    agent = RalphLoopAgent()
    
    if args.status:
        agent.show_status()
        return
    
    agent.run_loop(
        max_iterations=args.max_iterations,
        category=args.category,
        feature_id=args.feature,
        once=args.once
    )


if __name__ == "__main__":
    main()
