#!/bin/bash

# ============================================================================
# Ralph-Loop: AI Agent Integration for Continuous Development
# ============================================================================
#
# This script integrates with AI coding agents to implement features
# in a continuous loop until all features are complete.
#
# Usage:
#   ./ralph-loop-ai.sh [--dry-run] [--max N]
#
# The script will:
# 1. Find the next pending feature
# 2. Generate implementation instructions
# 3. Call the AI agent to implement
# 4. Test and verify
# 5. Commit if successful
# 6. Repeat
#
# ============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m'

# Config
DRY_RUN=false
MAX_ITERATIONS=100
ITERATION=0
COMPLETED=0

# Parse args
while [[ $# -gt 0 ]]; do
    case $1 in
        --dry-run) DRY_RUN=true; shift ;;
        --max) MAX_ITERATIONS="$2"; shift 2 ;;
        *) shift ;;
    esac
done

cd "$PROJECT_ROOT"

# ============================================================================
# Functions
# ============================================================================

get_next_feature() {
    python3 << 'PY'
import json
try:
    with open('.agent/features.json', 'r') as f:
        data = json.load(f)
    pending = [f for f in data.get('features', []) if not f.get('passes', False)]
    priority = {'critical': 0, 'high': 1, 'medium': 2, 'low': 3}
    pending.sort(key=lambda x: priority.get(x.get('priority', 'medium'), 2))
    if pending:
        f = pending[0]
        print(f"{f['id']}|{f.get('priority','medium')}|{f.get('category','')}|{f['description']}")
        for step in f.get('steps', []):
            print(f"STEP:{step}")
except: pass
PY
}

get_stats() {
    python3 << 'PY'
import json
try:
    with open('.agent/features.json', 'r') as f:
        data = json.load(f)
    features = data.get('features', [])
    total = len(features)
    done = sum(1 for f in features if f.get('passes', False))
    print(f"{total}|{done}|{total-done}|{round(done/total*100,1) if total else 0}")
except: print("0|0|0|0")
PY
}

show_header() {
    echo ""
    echo -e "${MAGENTA}╔══════════════════════════════════════════════════════════╗${NC}"
    echo -e "${MAGENTA}║           Ralph-Loop: AI Agent Development               ║${NC}"
    echo -e "${MAGENTA}╚══════════════════════════════════════════════════════════╝${NC}"
    echo ""
    local stats=$(get_stats)
    local total=$(echo "$stats" | cut -d'|' -f1)
    local done=$(echo "$stats" | cut -d'|' -f2)
    local pending=$(echo "$stats" | cut -d'|' -f3)
    local pct=$(echo "$stats" | cut -d'|' -f4)
    echo -e "  ${GREEN}✓${NC} Completed: ${done}/${total} (${pct}%)"
    echo -e "  ${YELLOW}⏳${NC} Pending: ${pending} features"
    echo ""
}

generate_task_prompt() {
    local feature_id="$1"
    local priority="$2"
    local category="$3"
    local description="$4"
    shift 4
    local steps=("$@")
    
    cat << EOF
# Ralph-Loop Task: ${feature_id}

## Priority: ${priority} | Category: ${category}

### Description
${description}

### Verification Steps
$(for step in "${steps[@]}"; do echo "- [ ] ${step}"; done)

### Your Task

Implement this feature following these guidelines:

1. **Understand the Requirement**: Read the description carefully
2. **Check Existing Code**: Look at similar implementations in the codebase
3. **Implement Incrementally**: Make small, testable changes
4. **Test Your Code**: Ensure all verification steps pass
5. **Commit Clean Code**: No half-implemented features

### After Implementation

1. Update .agent/features.json - set this feature's "passes" to true
2. Commit with message: [agent] feat(${feature_id}): ${description}
3. Run ./.agent/session-start.sh to see next task

---
*Generated by Ralph-Loop at $(date)*
EOF
}

# ============================================================================
# Main Loop
# ============================================================================

show_header

while [ $ITERATION -lt $MAX_ITERATIONS ]; do
    ITERATION=$((ITERATION + 1))
    
    # Get next feature
    feature_data=$(get_next_feature)
    
    if [ -z "$feature_data" ]; then
        echo -e "${GREEN}✨ All features complete!${NC}"
        break
    fi
    
    # Parse feature data
    feature_id=$(echo "$feature_data" | head -1 | cut -d'|' -f1)
    priority=$(echo "$feature_data" | head -1 | cut -d'|' -f2)
    category=$(echo "$feature_data" | head -1 | cut -d'|' -f3)
    description=$(echo "$feature_data" | head -1 | cut -d'|' -f4)
    
    # Get steps
    steps=()
    while IFS= read -r line; do
        if [[ "$line" == STEP:* ]]; then
            steps+=("${line#STEP:}")
        fi
    done <<< "$feature_data"
    
    # Show task
    echo ""
    echo -e "${MAGENTA}═══════════════════════════════════════════════════════════${NC}"
    echo -e "${MAGENTA}Iteration #${ITERATION}: ${feature_id}${NC}"
    echo -e "${MAGENTA}═══════════════════════════════════════════════════════════${NC}"
    echo ""
    echo -e "${BLUE}Priority:${NC} ${priority}"
    echo -e "${BLUE}Category:${NC} ${category}"
    echo -e "${BLUE}Description:${NC} ${description}"
    echo ""
    echo -e "${CYAN}Verification Steps:${NC}"
    for step in "${steps[@]}"; do
        echo -e "  ${CYAN}○${NC} ${step}"
    done
    echo ""
    
    if [ "$DRY_RUN" = true ]; then
        echo -e "${YELLOW}[DRY RUN] Would implement this feature${NC}"
        echo ""
        echo -e "${GREEN}Task prompt would be generated at: .agent/ralph-current-task.md${NC}"
        # Exit after one iteration in dry-run mode
        break
    fi
    
    # Generate task prompt and save
    task_prompt=$(generate_task_prompt "$feature_id" "$priority" "$category" "$description" "${steps[@]}")
    echo "$task_prompt" > "$PROJECT_ROOT/.agent/ralph-current-task.md"
    
    echo -e "${GREEN}Task file generated: .agent/ralph-current-task.md${NC}"
    echo ""
    
    # Call iFlow to implement the feature
    iflow_prompt="请阅读并执行 .agent/prompts/coding-agent.md 的要求，完成功能: ${feature_id} - ${description}"
    
    if command -v iflow &> /dev/null; then
        echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
        echo -e "${CYAN}Calling iFlow to implement...${NC}"
        echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
        echo ""
        
        if iflow -y -p "$iflow_prompt"; then
            echo ""
            echo -e "${GREEN}✓ iFlow completed successfully${NC}"
            COMPLETED=$((COMPLETED + 1))
        else
            echo ""
            echo -e "${RED}✗ iFlow failed, stopping loop${NC}"
            break
        fi
    else
        echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
        echo -e "${YELLOW}iFlow command not found.${NC}"
        echo -e "${YELLOW}Please implement manually and run this script again.${NC}"
        echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
        break
    fi
done

echo ""
show_header
